# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/emio_pins.xdc

# XDC: new/bitgen.xdc

# Block Designs: bd/zusys/zusys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys || ORIG_REF_NAME==zusys} -quiet] -quiet

# IP: bd/zusys/ip/zusys_inv_0_0/zusys_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_inv_0_0 || ORIG_REF_NAME==zusys_inv_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_zynq_ultra_ps_e_0_0/zusys_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==zusys_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: bd/zusys/zusys_ooc.xdc
