set_property SRC_FILE_INFO {cfile:/home/bopcb/work/vivado/pcb361_dp2/pcb361_dp2.srcs/constrs_1/new/emio_pins.xdc rfile:../../../pcb361_dp2.srcs/constrs_1/new/emio_pins.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C7 [get_ports dp_aux_data_out_0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E7 [get_ports dp_aux_data_in_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D2 [get_ports {dp_aux_data_oe[0]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G4 [get_ports dp_hot_plug_detect_0]
